mysite/RSS/urls.py
from django.urls import path, include

from .views import (
    ArticlesListView,
    ArticleDetailView,
    LatestArticlesFeed,
)

app_name = 'rss'

urlpatterns = [
    path('articles/', ArticlesListView.as_view(), name='articles'),
    path('articles/<int:pk>/', ArticleDetailView.as_view(), name='article'),
    path('articles/latest/feed/', LatestArticlesFeed(), name='articles-feed'),
]

mysite/blogapp/urls.py
from django.urls import path


from .views import ArticlesListView


app_name = "blogapp"

urlpatterns = [
    path('articles/', ArticlesListView.as_view(), name='blog-articles')
]

mysite/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from django.views.decorators.cache import cache_page


from .views import (
    get_cookie_view,
    set_cookie_view,
    set_session_view,
    get_session_view,
    MyLogoutView,
    AboutMeView,
    RegisterView,
    FooBarView,
    UsersListView,
    UserDetailsView,
)

app_name = "myauth"

urlpatterns = [
    # path("login/", login_view, name="login"),
    path(
        "login/",
        LoginView.as_view(
            template_name="myauth/login.html",
            redirect_authenticated_user=True,
        ),
        name="login",
    ),
    # path("logout/", logout_view, name="logout"),
    path("logout/", MyLogoutView.as_view(), name="logout"),
    path("about-me/", AboutMeView.as_view(), name="about-me"),
    path("register/", RegisterView.as_view(), name="register"),

    path("cookie/get/", get_cookie_view, name="cookie-get"),
    path("cookie/set/", set_cookie_view, name="cookie-set"),

    path("session/set/", set_session_view, name="session-set"),
    path("session/get/", get_session_view, name="session-get"),

    path("foo-bar/", FooBarView.as_view(), name="foo-bar"),
    path('', UsersListView.as_view(), name='users-list'),
    path('user/<int:pk>/', UserDetailsView.as_view(), name='user-details'),
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

from shopapp.views import ShopMainView
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

from .sitemaps import sitemaps

urlpatterns = [
    path('', ShopMainView.as_view(), name='main_view'),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls, name='admin_panel'),
    path('shop/', include('shopapp.urls')),
    path('accounts/', include('myauth.urls')),
    path('blogapp/', include('blogapp.urls')),
    path('RSS/', include('RSS.urls')),
    path(
        'sitemap.xml',
        sitemap,
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap',
    ),

    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('api/', include('myapiapp.urls')),


]


if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )
    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls')),
    )

mysite/shopapp/urls.py
from django.urls import path, include
from django.views.decorators.cache import cache_page


from rest_framework.routers import DefaultRouter


from .views import (
    ShopIndexView,
    ProductsListView,
    ProductDetailsView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    ProductArchiveView,
    ProductsDataExportView,
    ProductViewSet,
    OrdersListView,
    OrderDetailsView,
    OrderCreateView,
    OrderUpdateView,
    OrderDeleteView,
    OrdersDataExportView,
    OrderViewSet,
    LatestProductsFeed,
    UserOrdersListView,
    UserOrdersDataExportView,
)

app_name = "shopapp"

routers = DefaultRouter()
routers.register('products', ProductViewSet)
routers.register('orders', OrderViewSet)

urlpatterns = [
    # здесь пример применения декоратора cache_page к view-классу:
    # path("", cache_page(60 * 3)(ShopIndexView.as_view()), name="index"),

    path("", ShopIndexView.as_view(), name="index"),


    path('api/', include(routers.urls)),
    path("products/", ProductsListView.as_view(), name="products_list"),
    path("products/<int:pk>/", ProductDetailsView.as_view(), name="product_details"),
    path('products/create/', ProductCreateView.as_view(), name='product_create'),
    path("products/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"),
    path("products/<int:pk>/delete/", ProductDeleteView.as_view(), name="product_delete"),
    path("products/<int:pk>/archive/", ProductArchiveView.as_view(), name="product_archive"),
    path("products/export/", ProductsDataExportView.as_view(), name="products-export"),

    path('products/feed/', LatestProductsFeed(), name='products-feed'),

    path("orders/", OrdersListView.as_view(), name="orders_list"),
    path("orders/<int:pk>/", OrderDetailsView.as_view(), name="order_details"),
    path("orders/create/", OrderCreateView.as_view(), name="order_create"),
    path("orders/<int:pk>/update/", OrderUpdateView.as_view(), name="order_update"),
    path("orders/<int:pk>/delete/", OrderDeleteView.as_view(), name="order_delete"),
    path("orders/export/", OrdersDataExportView.as_view(), name="orders-export"),

    path("users/<int:pk>/orders/", UserOrdersListView.as_view(), name="user_orders"),
    path("users/<int:user_id>/orders/export/", UserOrdersDataExportView.as_view(), name="user_orders_export")
]

mysite/shopapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


def product_preview_directory_path(instance: 'Product', filename: str) -> str:
    return f'products/product_{instance.pk}/preview/{filename}'


class Product(models.Model):
    # обязательно синтаксис такой должен быть, для указания ссылки в документации:
    """
    Модель Product представляет товар, который можно продавать в интернет-магазине.

    Заказы тут: `shopapp.Order`
    """
    class Meta:
        ordering = ["name", "price"]

    name = models.CharField(max_length=100, db_index=True)
    description = models.TextField(null=False, blank=True, db_index=True)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.PROTECT)
    archived = models.BooleanField(default=False)
    preview = models.ImageField(null=True, blank=True, upload_to=product_preview_directory_path)

    def __str__(self):
        return f"Product(pk={self.pk}, name={self.name!r})"

    def get_absolute_url(self):
        return reverse('shopapp:product_details', kwargs={'pk': self.pk})


def product_images_directory_path(instance: 'ProductImage', filename: str) -> str:
    return f'products/product_{instance.product.pk}/preview/{filename}'


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to=product_images_directory_path)
    description = models.CharField(max_length=200, null=False, blank=True)


class Order(models.Model):
    delivery_address = models.TextField(null=True, blank=True)
    promocode = models.CharField(max_length=20, null=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name="orders")
    receipt = models.FileField(null=True, upload_to='orders/receipts/')

    def get_absolute_url(self):
        return reverse('shopapp:order_details', kwargs={'pk': self.pk})

mysite/shopapp/forms.py
from django import forms

from .models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = 'name', 'price', 'description', 'discount', 'preview'

    # adding a new field:
    images = forms.ImageField(
        # to have an option of adding many images at the time, we have to tag this widget:
        widget=forms.ClearableFileInput(attrs={"multiple": True})
    )


class CSVImportForm(forms.Form):
    csv_file = forms.FileField()

mysite/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <title>
    {% block title %}
      Base Title
    {% endblock %}
  </title>
</head>
<body>

{% block link %}

    <div style="display: flex; justify-content: space-around;">
        <div><a href="{% url 'main_view' %}">Main Page</a></div>
        <div><a href="{% url 'myauth:register' %}">Register new user</a></div>
        <div>
          {% if user.is_authenticated %}
            <a href="{% url 'myauth:logout' %}">Logout</a>
          {% else %}
            <a href="{% url 'myauth:login' %}">Login</a>
          {% endif %}
        </div>
    </div>
{% endblock %}

{% block body %}
  Base body
{% endblock %}

</body>
</html>

mysite/shopapp/templates/shopapp/order-details.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Order # {{ object.pk }} details
{% endblock %}

{% block body %}
  <h1>Order #{{ object.pk }}:</h1>

        <div>
          <p>Order by {% firstof object.user.first_name object.user.username %}</p>
          <p>Promocode: <code>{{ object.promocode }}</code></p>
          <p>Delivery address: {{ object.delivery_address }}</p>
          <div>
            Product in order:
            <ul>
              {% for product in object.products.all %}
                <li>{{ product.name }} for ${{ product.price }}</li>
              {% endfor %}

            </ul>
          </div>

        </div>

<br>

<div>
  <a href="{% url 'shopapp:order_update' pk=object.pk %}">
    Update Order
  </a><br>
  <a href="{% url 'shopapp:order_delete' pk=object.pk %}">
    Delete Order
  </a><br><br>
  <a href="{% url 'shopapp:orders_list' %}">
    Back to orders list
  </a>
</div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Confirm delete {{ object.name }}
{% endblock %}



{% block body %}
<h1>Confirm delete {{ object.name }}</h1>
<p>Are you sure want to delete {{ object.name }}?</p>
<br>
<br>
<br>
<div>
  <a href="{% url 'shopapp:order_details' pk=object.pk %}">
    Back to order #{{ object.pk}}
  </a>
</div>

<div>
    <form method="post">
        {% csrf_token %}

         {{ form.as_p }}
        <button type="submit">Delete</button>
    </form>
</div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Orders list
{% endblock %}

{% block body %}
  <h1>Orders:</h1>
  {% if object_list %}
    <div>
      {% for order in object_list %}
        <div>
          <p><a href="{% url 'shopapp:order_details' pk=order.pk %}">Details # {{ order.pk }}</a></p>
          <p>Order by: {% firstof order.user.first_name order.user.username %}</p>
          <p>Promocode: <code>{{ order.promocode }}</code></p>
          <p>Delivery address: {{ order.delivery_address }}</p>
          <div>
            Product in order:
            <ul>
              {% for product in order.products.all %}
                <li>{{ product.name }} for ${{ product.price }}</li>
              {% endfor %}

            </ul>
          </div>

        </div>
      {% endfor %}

    </div>
  {% else %}
    <h3>No orders yet</h3>
  {% endif %}

<br>
<ul>
  <li>
    {% if user.is_authenticated %}
      <a href="{% url 'shopapp:order_create' %}">Make order</a>
    {% else %}
      <p>You have to be logged in, to create a new order.</p>
    {% endif %}
  </li><br>
  <li>
    {% if perms.shopapp.update_order %}
      <a href="{% url 'shopapp:orders-export' %}">Export orders</a>
    {% else %}
      <p>You don't have a permission, to export orders.</p>
    {% endif %}
  </li>
</ul>

{% endblock %}

mysite/shopapp/templates/shopapp/order_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Update order
{% endblock %}



{% block body %}
<h1>Update order:</h1>
<div>
    <form method="post">
        {% csrf_token %}

         {{ form.as_p }}
        <button type="submit">Update</button>
    </form>
</div>

<div>
  <a href="{% url 'shopapp:order_details' pk=object.pk %}">
    Back to order #{{ object.pk}}
  </a>
</div>
{% endblock %}

mysite/shopapp/templates/shopapp/product-details.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Product #{{ product.pk }}
{% endblock %}



{% block body %}
<h1>Product {{ product.name }}</h1>
<div>
  <div>Description: {{ product.description }}</div>
  <div>Created by: {{ product.created_by }}</div>
  <div>Price: {{ product.price }}</div>
  <div>Discount: {{ product.discount }}</div>
  <div>Archived: {{ product.archived }}</div>
    {% if product.preview %}
      <div>
        <img src="{{ product.preview.url }}" alt="{{ product.name }}" title="{{ product.description }}" width="200">
      </div>
    {% endif %}
</div>
<br>
<h3>Images:</h3>
<div>
<!--  because we got 'to many' connection, we have to tag .all at the end  -->
  {% for img in product.images.all %}
    <div>
      <img src="{{ img.image.url }}" alt="img.image.name" width="200">
    </div>
    <div>
      {{ img.description }}
    </div>
<!--  if no iterations was made (product.images.all was empty)-->
  {% empty %}
     <div>No images uploaded yet</div>
  {% endfor %}

</div>
<br>

<div>
  {% if perms.shopapp.delete_product or perms.shopapp.update_product %}
  <a href="{% url 'shopapp:product_update' pk=object.pk %}">
    Update product
  </a><br>
  <a href="{% url 'shopapp:product_archive' pk=object.pk %}">
    Archive product
  </a><br>
  <a href="{% url 'shopapp:product_delete' pk=object.pk %}">
    Delete product
  </a>
  {% endif %}
  <br><br>
  <a href="{% url 'shopapp:products_list' %}">
    Back to products list
  </a>
</div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_confirm_archive.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Confirm archive {{ object.name }}
{% endblock %}



{% block body %}
<h1>Confirm archive {{ object.name }}</h1>
<p>Are you sure want to archive {{ object.name }}?</p>
<br>
<br>
<br>
<div>
  <a href="{% url 'shopapp:product_details' pk=object.pk %}">
    Back to product #{{ object.pk}}
  </a>
</div>

<div>
    <form method="post">
        {% csrf_token %}

         {{ form.as_p }}
        <button type="submit">Archive</button>
    </form>
</div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Confirm delete {{ object.name }}
{% endblock %}



{% block body %}
<h1>Confirm delete {{ object.name }}</h1>
<p>Are you sure want to delete {{ object.name }}?</p>
<br>
<br>
<br>
<div>
  <a href="{% url 'shopapp:product_details' pk=object.pk %}">
    Back to product #{{ object.pk}}
  </a>
</div>

<div>
    <form method="post">
        {% csrf_token %}

         {{ form.as_p }}
        <button type="submit">Delete</button>
    </form>
</div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Create product
{% endblock %}

{% block body %}
<h1>Create product</h1>
<div>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create</button>
  </form>
</div>

<div>
  <a href="{% url 'shopapp:products_list' %}">
    Back to products list
  </a>
</div>
{% endblock %}

mysite/shopapp/templates/shopapp/products-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Products list
{% endblock %}

{% block body %}
  <h1>Products:</h1>
  {% if products %}
    <div>
    {% for product in products %}
      <div>
        <p>Name: <a href="{% url 'shopapp:product_details' pk=product.pk %}">{{ product.name }}</a></p>
        <p>Price: {{ product.price }}</p>
        <p>Discount: {% firstof product.discount 'no discount' %}</p>
      </div>
      {% if product.preview %}
        <div>
          <img src="{{ product.preview.url }}" alt="{{ product.name }}" title="{{ product.description }}" width="200">
        </div>
      {% endif %}
      <br>
    {% endfor %}

    </div>

  {% else %}
    <h3>No products yet</h3>
  {% endif %}


{% if perms.shopapp.add_product %}
<br>
<ul>
  <li><a href="{% url 'shopapp:product_create' %}">Create a new product</a></li><br>
  <li><a href="{% url 'shopapp:products-export' %}">Export products</a></li>
</ul>
{% else %}
<p>You don't have a permission, to create a new product or export products.</p>
{% endif %}
{% endblock %}

mysite/shopapp/templates/shopapp/products_changelist.html
<!--выпоняем наследование от админского шаблона-->
{% extends 'admin/change_list.html' %}

<!--блок, где находятся все кнопки:-->
{% block object-tools-items %}
<!--чтобы все админские ссылки правильно подгружались:-->
{% load admin_urls %}

<!--объявляем новую кнопку:-->
    <li>
        <a href="{% url 'admin:import_products_csv' %}" class="addlink">
            Import CSV
        </a>
    </li>
<!--вызываем родительский блок, который мы выше переопределили:-->
    {{ block.super }}

{% endblock %}

mysite/shopapp/templates/shopapp/shop-index.html
{% extends 'shopapp/base.html' %}
{% load cache %}

{% block title %}
  Shop Index
{% endblock %}


{% block body %}
  <h1>Здесь КЭШИРОВАНИЕ в шаблоне! Hello Shop Index!</h1>

  <div>
    <ul>
      {% for name, price in products %}
        <li>{{ name }} ({{ name|length }}) for ${{ price }}</li>
        {% if name|length_is:'7' %}
          <span>Lucky product!</span>
        {% endif %}
      {% empty %}
        No products here
      {% endfor %}

    </ul>
  </div>

  <div>
    Time running: {{ time_running }}
  </div>



<!-- 100 - время жизни кэша в секундах,
lorem в данном случае - переменная (по ней будет доступен кэш), которая  задается прямо здесь и может быть любой.
тут же можно добавлять другие переменные, которые позволят более тонко настраивать кэш, например - айди или
имя пользолвателя для которого этот кэш.

 -->
  {% cache 100 lorem %}
  <div>
    {% lorem 3 p random %}
  </div>
  {% endcache %}




{% endblock %}

mysite/shopapp/templates/shopapp/shop-main.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Super DJANGO shop SITE
{% endblock %}


{% block link %}
    <div style="display: flex; justify-content: space-around;">
        <div><a href="{% url 'myauth:register' %}">Register new user</a></div>
        <div>
            {% if user.is_authenticated %}
                <a href="{% url 'myauth:logout' %}">Logout</a>
            {% else %}
                <a href="{% url 'myauth:login' %}">Login</a>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block body %}
  <h1 align="center">Hello, this is main page of Super DJANGO shop SITE!</h1>
  <H2>This is our main services below:</H2>
  <ul>
    <li><a href="{% url 'blogapp:blog-articles' %}">
      NEW: Articles list
    </a></li>
  </ul>
  <div>
    {% lorem 2 p random %}
  </div>
  <ul>
    <li><a href="{% url 'shopapp:products_list' %}">
      Available products List
    </a></li>
  </ul>
  <div>
    {% lorem 3 p random %}
  </div>

  <ul>
    <li><a href="{% url 'shopapp:orders_list' %}">
      Created orders List
    </a></li>
  </ul>
  <div>
    {% lorem 3 p random %}
  </div>

  <div>
    Time running: {{ time_running }}
  </div>

<h2>Have a look at our secondary services below:</h2>
    <ol>
        <li><a href="{% url 'myauth:users-list' %}">user</a></li>
        <li><a href="/admin/">Admin panel</a></li>
        <li><a href="{% url 'myauth:cookie-set' %}">Cookie set</a></li>
        <li><a href="{% url 'myauth:cookie-get' %}">Cookie get</a></li>
        <li><a href="{% url 'myauth:session-set' %}">Session set</a></li>
        <li><a href="{% url 'myauth:session-get' %}">Session get</a></li>
    </ol>

{% endblock %}

mysite/shopapp/templates/shopapp/user_orders.html
{% extends 'shopapp/base.html' %}
{% load cache %}

{% block title %}
    User {{ user.username }}
{% endblock %}



{% block body %}
    {% if orders %}
        <h1>Пользователь <a href="{% url 'myauth:user-details' pk=owner.pk %}">{{ owner.username }}</a> выполнил следующие заказы:</h1>
        <h6>random num:</h6>
        <p>{% now "u" %}</p>
        {% cache 250 orders_cache user.username %}
            <ul>
            {% for order in orders %}
                <li>Заказ <a href="{% url 'shopapp:order_details' pk=order %}">#{{order}}</a></li>
            {% endfor %}
            </ul>
            <h6>random text:</h6>
            <p>{% lorem 1 p random %}</p>
        {% endcache %}
    {% else %}
        <h1>У пользователя <a href="{% url 'myauth:user-details' pk=owner.pk %}">{{ owner.username }}</a> ещё нет заказов.</h1>
        <h2>You are: <a href="{% url 'myauth:user-details' pk=user.pk %}">{{ user.username }}</a></h2>
    {% endif %}
{% endblock %}